[2025-09-05T12:51:42.612+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: file_upload_trigger.consume_kafka_and_run_pipeline manual__2025-09-05T12:51:41.646677+00:00 [queued]>
[2025-09-05T12:51:42.635+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: file_upload_trigger.consume_kafka_and_run_pipeline manual__2025-09-05T12:51:41.646677+00:00 [queued]>
[2025-09-05T12:51:42.635+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-09-05T12:51:42.655+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): consume_kafka_and_run_pipeline> on 2025-09-05 12:51:41.646677+00:00
[2025-09-05T12:51:42.662+0000] {standard_task_runner.py:57} INFO - Started process 668 to run task
[2025-09-05T12:51:42.667+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'file_upload_trigger', 'consume_kafka_and_run_pipeline', 'manual__2025-09-05T12:51:41.646677+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/file_upload_trigger.py', '--cfg-path', '/tmp/tmpf__7flrs']
[2025-09-05T12:51:42.673+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask consume_kafka_and_run_pipeline
[2025-09-05T12:51:42.790+0000] {task_command.py:416} INFO - Running <TaskInstance: file_upload_trigger.consume_kafka_and_run_pipeline manual__2025-09-05T12:51:41.646677+00:00 [running]> on host 353891d48c75
[2025-09-05T12:51:42.936+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='file_upload_trigger' AIRFLOW_CTX_TASK_ID='consume_kafka_and_run_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-09-05T12:51:41.646677+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-05T12:51:41.646677+00:00'
[2025-09-05T12:51:42.942+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: connecting to kafka:9092 [('172.18.0.6', 9092) IPv4]
[2025-09-05T12:51:42.946+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.6', 9092)]>: Broker version identified as 2.6
[2025-09-05T12:51:42.947+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.6', 9092)]>: Connection complete.
[2025-09-05T12:51:42.949+0000] {consumer.py:120} WARNING - group_id is None: disabling auto-commit.
[2025-09-05T12:51:42.949+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('file_uploads',)
[2025-09-05T12:51:42.952+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('file_uploads', 0)]
[2025-09-05T12:51:42.954+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: connecting to kafka:9092 [('172.18.0.6', 9092) IPv4]
[2025-09-05T12:51:42.955+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connected> [IPv4 ('172.18.0.6', 9092)]>: Connection complete.
[2025-09-05T12:51:42.956+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.6', 9092)]>: Closing connection. 
[2025-09-05T12:51:42.960+0000] {fetcher.py:418} INFO - Resetting offset for partition ('file_uploads', 0) to offset 0.
[2025-09-05T12:58:10.863+0000] {conn.py:1163} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connected> [IPv4 ('172.18.0.6', 9092)]>: socket disconnected
[2025-09-05T12:58:10.865+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connected> [IPv4 ('172.18.0.6', 9092)]>: Closing connection. KafkaConnectionError: socket disconnected
[2025-09-05T12:58:10.868+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T12:58:10.870+0000] {fetcher.py:786} ERROR - Fetch to node 1002 failed: KafkaConnectionError: socket disconnected
[2025-09-05T12:58:10.875+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: connecting to kafka:9092 [('172.18.0.6', 9092) IPv4]
[2025-09-05T12:58:10.880+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T12:58:10.881+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T12:58:10.882+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T12:58:10.990+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: connecting to kafka:9092 [('172.18.0.6', 9092) IPv4]
[2025-09-05T12:58:10.992+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T12:58:10.992+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T12:58:10.993+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T12:58:11.163+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: connecting to kafka:9092 [('172.18.0.6', 9092) IPv4]
[2025-09-05T12:58:11.164+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T12:58:11.165+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T12:58:11.165+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T12:58:11.564+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: connecting to kafka:9092 [('172.18.0.6', 9092) IPv4]
[2025-09-05T12:58:11.565+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T12:58:11.566+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T12:58:11.567+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T12:58:12.303+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: connecting to kafka:9092 [('172.18.0.6', 9092) IPv4]
[2025-09-05T12:58:12.304+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T12:58:12.305+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T12:58:12.305+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T12:58:14.150+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: connecting to kafka:9092 [('172.18.0.6', 9092) IPv4]
[2025-09-05T12:58:14.151+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T12:58:14.151+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T12:58:14.151+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T12:58:17.834+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-05T12:58:17.835+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T12:58:17.837+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T12:58:17.838+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T12:58:22.965+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-05T12:58:22.966+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-05T13:04:25.806+0000] {conn.py:1163} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: socket disconnected
[2025-09-05T13:04:25.809+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: socket disconnected
[2025-09-05T13:04:25.811+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:04:25.812+0000] {fetcher.py:786} ERROR - Fetch to node 1002 failed: KafkaConnectionError: socket disconnected
[2025-09-05T13:04:25.819+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-05T13:04:25.822+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T13:04:25.825+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T13:04:25.830+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:04:25.921+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-05T13:04:25.922+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T13:04:25.923+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T13:04:25.923+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:04:26.124+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-05T13:04:26.125+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T13:04:26.125+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T13:04:26.126+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:04:26.544+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-05T13:04:26.544+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T13:04:26.545+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T13:04:26.545+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:04:27.186+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-05T13:04:27.187+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T13:04:27.188+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T13:04:27.188+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:04:28.728+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-05T13:04:28.728+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T13:04:28.729+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T13:04:28.730+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:04:31.936+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-05T13:04:31.937+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: DNS lookup failed for kafka:9092 (0)
[2025-09-05T13:04:31.937+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-09-05T13:04:31.938+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:04:38.151+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-05T13:04:38.152+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T13:04:38.153+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T13:04:38.153+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:04:49.179+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-05T13:04:49.180+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: DNS lookup failed for kafka:9092 (0)
[2025-09-05T13:04:49.180+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-09-05T13:04:49.181+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:05:11.994+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-05T13:05:11.994+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: DNS lookup failed for kafka:9092 (0)
[2025-09-05T13:05:11.995+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-09-05T13:05:11.995+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:05:44.262+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-05T13:05:44.263+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: DNS lookup failed for kafka:9092 (0)
[2025-09-05T13:05:44.264+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-09-05T13:05:44.264+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:06:17.102+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-05T13:06:17.103+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: DNS lookup failed for kafka:9092 (0)
[2025-09-05T13:06:17.103+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-09-05T13:06:17.104+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:06:46.217+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-05T13:06:46.217+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: DNS lookup failed for kafka:9092 (0)
[2025-09-05T13:06:46.218+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-09-05T13:06:46.218+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:07:10.936+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-05T13:07:10.937+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: DNS lookup failed for kafka:9092 (0)
[2025-09-05T13:07:10.937+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-09-05T13:07:10.937+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:07:46.620+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-05T13:07:46.621+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: DNS lookup failed for kafka:9092 (0)
[2025-09-05T13:07:46.621+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-09-05T13:07:46.622+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
