[2025-09-05T12:11:20.817+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: file_upload_trigger.consume_kafka_and_run_pipeline manual__2025-09-05T12:09:34.527647+00:00 [queued]>
[2025-09-05T12:11:20.832+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: file_upload_trigger.consume_kafka_and_run_pipeline manual__2025-09-05T12:09:34.527647+00:00 [queued]>
[2025-09-05T12:11:20.833+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-09-05T12:11:20.856+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): consume_kafka_and_run_pipeline> on 2025-09-05 12:09:34.527647+00:00
[2025-09-05T12:11:20.864+0000] {standard_task_runner.py:57} INFO - Started process 269 to run task
[2025-09-05T12:11:20.869+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'file_upload_trigger', 'consume_kafka_and_run_pipeline', 'manual__2025-09-05T12:09:34.527647+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/file_upload_trigger.py', '--cfg-path', '/tmp/tmp1i082k_y']
[2025-09-05T12:11:20.873+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask consume_kafka_and_run_pipeline
[2025-09-05T12:11:20.976+0000] {task_command.py:416} INFO - Running <TaskInstance: file_upload_trigger.consume_kafka_and_run_pipeline manual__2025-09-05T12:09:34.527647+00:00 [running]> on host 353891d48c75
[2025-09-05T12:11:21.132+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='file_upload_trigger' AIRFLOW_CTX_TASK_ID='consume_kafka_and_run_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-09-05T12:09:34.527647+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-05T12:09:34.527647+00:00'
[2025-09-05T12:11:21.139+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: connecting to kafka:9092 [('172.18.0.6', 9092) IPv4]
[2025-09-05T12:11:21.150+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.6', 9092)]>: Broker version identified as 2.6
[2025-09-05T12:11:21.151+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.6', 9092)]>: Connection complete.
[2025-09-05T12:11:21.154+0000] {consumer.py:120} WARNING - group_id is None: disabling auto-commit.
[2025-09-05T12:11:21.155+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('file_uploads',)
[2025-09-05T12:11:21.170+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('file_uploads', 0)]
[2025-09-05T12:11:21.173+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: connecting to kafka:9092 [('172.18.0.6', 9092) IPv4]
[2025-09-05T12:11:21.175+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connected> [IPv4 ('172.18.0.6', 9092)]>: Connection complete.
[2025-09-05T12:11:21.175+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.6', 9092)]>: Closing connection. 
[2025-09-05T12:11:21.201+0000] {fetcher.py:418} INFO - Resetting offset for partition ('file_uploads', 0) to offset 1.
[2025-09-05T12:39:58.258+0000] {cluster.py:313} WARNING - Topic file_uploads is not available during auto-create initialization
[2025-09-05T12:39:58.259+0000] {subscription_state.py:254} INFO - Updated partition assignment: []
[2025-09-05T12:44:58.262+0000] {cluster.py:316} ERROR - Topic file_uploads not found in cluster metadata
[2025-09-05T12:49:58.301+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('file_uploads', 0)]
[2025-09-05T12:49:58.304+0000] {fetcher.py:418} INFO - Resetting offset for partition ('file_uploads', 0) to offset 0.
[2025-09-05T12:58:10.862+0000] {conn.py:1163} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connected> [IPv4 ('172.18.0.6', 9092)]>: socket disconnected
[2025-09-05T12:58:10.865+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connected> [IPv4 ('172.18.0.6', 9092)]>: Closing connection. KafkaConnectionError: socket disconnected
[2025-09-05T12:58:10.867+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T12:58:10.870+0000] {fetcher.py:786} ERROR - Fetch to node 1002 failed: KafkaConnectionError: socket disconnected
[2025-09-05T12:58:10.873+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: connecting to kafka:9092 [('172.18.0.6', 9092) IPv4]
[2025-09-05T12:58:10.876+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T12:58:10.879+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T12:58:10.882+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T12:58:10.977+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: connecting to kafka:9092 [('172.18.0.6', 9092) IPv4]
[2025-09-05T12:58:10.978+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T12:58:10.978+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T12:58:10.979+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T12:58:11.178+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: connecting to kafka:9092 [('172.18.0.6', 9092) IPv4]
[2025-09-05T12:58:11.179+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T12:58:11.180+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T12:58:11.181+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T12:58:11.517+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: connecting to kafka:9092 [('172.18.0.6', 9092) IPv4]
[2025-09-05T12:58:11.519+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T12:58:11.520+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T12:58:11.520+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T12:58:12.222+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: connecting to kafka:9092 [('172.18.0.6', 9092) IPv4]
[2025-09-05T12:58:12.223+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T12:58:12.223+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T12:58:12.224+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T12:58:14.002+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: connecting to kafka:9092 [('172.18.0.6', 9092) IPv4]
[2025-09-05T12:58:14.003+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T12:58:14.004+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T12:58:14.007+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T12:58:16.995+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-05T12:58:16.996+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T12:58:16.997+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T12:58:16.998+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T12:58:24.470+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-05T12:58:24.471+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-05T13:04:25.805+0000] {conn.py:1163} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: socket disconnected
[2025-09-05T13:04:25.808+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: socket disconnected
[2025-09-05T13:04:25.811+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:04:25.815+0000] {fetcher.py:786} ERROR - Fetch to node 1002 failed: KafkaConnectionError: socket disconnected
[2025-09-05T13:04:25.830+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-05T13:04:25.833+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T13:04:25.836+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T13:04:25.837+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:04:25.918+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-05T13:04:25.919+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T13:04:25.920+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T13:04:25.921+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:04:26.094+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-05T13:04:26.094+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T13:04:26.095+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T13:04:26.096+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:04:26.547+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-05T13:04:26.547+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T13:04:26.548+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T13:04:26.549+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:04:27.419+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-05T13:04:27.420+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T13:04:27.420+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T13:04:27.421+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:04:29.130+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-05T13:04:29.131+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T13:04:29.132+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T13:04:29.132+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:04:32.683+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-05T13:04:32.685+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: DNS lookup failed for kafka:9092 (0)
[2025-09-05T13:04:32.686+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-09-05T13:04:32.686+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:04:38.902+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-05T13:04:38.902+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-05T13:04:38.903+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-05T13:04:38.903+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:04:53.723+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-05T13:04:53.723+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: DNS lookup failed for kafka:9092 (0)
[2025-09-05T13:04:53.724+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-09-05T13:04:53.724+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:05:19.945+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-05T13:05:19.946+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: DNS lookup failed for kafka:9092 (0)
[2025-09-05T13:05:19.947+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-09-05T13:05:19.948+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:05:51.674+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-05T13:05:51.675+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: DNS lookup failed for kafka:9092 (0)
[2025-09-05T13:05:51.675+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-09-05T13:05:51.676+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:06:20.937+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-05T13:06:20.938+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: DNS lookup failed for kafka:9092 (0)
[2025-09-05T13:06:20.939+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-09-05T13:06:20.939+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:06:56.523+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-05T13:06:56.524+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: DNS lookup failed for kafka:9092 (0)
[2025-09-05T13:06:56.524+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-09-05T13:06:56.525+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:07:27.327+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-05T13:07:27.327+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: DNS lookup failed for kafka:9092 (0)
[2025-09-05T13:07:27.328+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-09-05T13:07:27.328+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
[2025-09-05T13:08:03.251+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-05T13:08:03.252+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: DNS lookup failed for kafka:9092 (0)
[2025-09-05T13:08:03.253+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1002 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-09-05T13:08:03.254+0000] {client_async.py:388} WARNING - Node 1002 connection failed -- refreshing metadata
